### ISSUE TITLE
FR: copy an image to the clipboard, paste it on Cud, get it inserted in the current file

### ISSUE THREAD

**Issue by quesada** [CudaText-addons/cuda_insert_pics#1]
Right now the UX for adding images is cumbersome:
1. copy to clipboard
2. paste it to file manager
3. give it a name
4. go to cuda
5. trigger 'insert pic'
6. find image on file browser
7. press enter

It'd be much easier to simply copy and paste, where everything else is taken care of for you. Big difference.

**Comment by Alexey-T** [comment]
Yes it would be handy. I'm little busy now, maybe later will see it.. patch for plugin is welcome.,

**Comment by Alexey-T** [comment]
python lib is needed for that.
https://pypi.org/project/pillow/
https://www.devdungeon.com/content/grab-image-clipboard-python-pillow#intro

Problem.
It is 

- huge, 2-3 Mb in zip
- it needs DLLs for Windows version - per x32/x64. and per python 3.6/3.7/3.8/3.9.

each combination needs seperate DLL: (x32, py 3.6), (x64, py 3.8) etc.
bad.

**Comment by Alexey-T** [comment]
maybe I could do this for $$ payment. or some other Cud user can do it.

**Comment by quesada** [comment]
Ugh! Pity.
It's not super important, more of a nice to have. But how much money are we
talking about?

**Comment by Alexey-T** [comment]
GH inserted email info to your post.

I don't need $$ right now, maybe better if you (or friend) makes some good video about Cud. not short.

**Comment by quesada** [comment]
Thanks, removed. 
Sure, I can do a video, no problem. It will be also educational for other members of the team who I'd like to get on board with this system :)

**Comment by Alexey-T** [comment]
OK, for a video,I ll try to add Cud API to 'paste the picture and save it to a file'. we won't need the PY lib then.

**Comment by Alexey-T** [comment]
(if I cannot add the API,I will make the Cud packages with that lib, for py 3.6 and x32/x64)

**Comment by quesada** [comment]
Hey Alexey,

Did you hear back from your colleague? About that differ integration with
seafile?

**Comment by Alexey-T** [comment]
personal info is left in your reply.     ............ I wait for replies from 2 mates. Oleh and Jairo. as I wrote in email...

**Comment by Alexey-T** [comment]
@quesada I made preparation of the API in 1.124.3 beta. let's wait for a video, then I will implenent FR for InsertPics plugin, OK?

**Comment by quesada** [comment]
Sounds good.

Just to give you a heads up, on my side I've been testing a bunch of
editors with typometer.  Looks like editing a long md file (my use case) is
problematic for most, including cudatext. The ghosting though is
cudatext-only, and makes me feel bothered enough that I prefer editing
markdown somewhere else. I'm sure I'm alone in being bothered by the
ghosting though.

**Comment by JairoMartinezA** [comment]
Hi @quesada 

How many lines have your md file?

Sorry I cannot catch at all this part: "The ghosting though" The English is not my native language.

**Comment by Alexey-T** [comment]
@JairoMartinezA see https://github.com/Alexey-T/CudaText/issues/3167

**Comment by quesada** [comment]
1650 lines

**Comment by Alexey-T** [comment]
Insert Pics plugin updated today. is has the new cmd: Insert picture from clipboard.
I still welcome some video, anyway, if you can.
